### ISSUE TITLE
Use index.html for React to display client's website

### ISSUE THREAD

**Issue by MikeN64** [MikeN64/ThoUpholsteryWebsite#4]
Change the default react page to the client's (Tho's Upholstery) page. When running `npm start`, the http://localhost:3000 should display the client's page.

Requirements:
`node <= v16.13.1`
`npm <= v8.1.2`

Action Steps:
1. Install the requirements
2. Check that the react-website is running properly. Click [here](https://reactjs.org/docs/create-a-new-react-app.html#create-react-app) for reference. Note: You do not have to run the `npx create-react-app` command.
3. Make `App.js` in `src` folder to look similar to `index.html`

**Comment by MikeN64** [comment]
Pause working on react project for now; react affected the deployment to fail

**Comment by Chromatist** [comment]
Back in business!!

**Comment by Chromatist** [comment]
Good enough! Let's break this into smaller tasks
